version: '3'

services:
    alert_bot:
        image: asvata/custom_alertmanager_bot:latest
        container_name: nodejs
        restart: unless-stopped
        env_file: .env
        environment:
            - MONGO_USER=$MONGO_USERNAME
            - MONGO_PASS=$MONGO_PASSWORD
            - JIRA_USER=$JIRA_USER
            - JIRA_PASS=$JIRA_PASS
            - TELEGRAM_TOKEN=$TELEGRAM_TOKEN
            - ASSIGNEE_USER=$ASSIGNEE_USER
            - MONGO_HOST=db
            - NODE_TLS_REJECT_UNAUTHORIZED=0
        ports:
            - "9090:9090"
        networks:
            - app-network

    db:
        image: mongo:4.1.8-xenial
        container_name: db
        restart: unless-stopped
        env_file: .env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
        volumes:  
            - dbdata:/data/db   
        networks:
            - app-network  
networks:
    app-network:
        driver: bridge

volumes:
    dbdata: